### ISSUE TITLE
big file upload above 2G failed.

### ISSUE THREAD

**Issue by kybird** [GREsau/localstack-persist#11]
localstack is running on docker desktop on windows.
here is localstack suspicious log
[localStack.txt](https://github.com/GREsau/localstack-persist/files/15073905/localStack.txt)

**Comment by GREsau** [comment]
What version of localstack-persist are you using?

**Comment by kybird** [comment]
i have tried 3 3.3.0 latest 
every recently version all the same.

and i think this is because of mulitpart upload
i modify configuration of aws s3 
s3 =
    max_concureent_requests = 1
    max_bandwidth = 10MB/s
    multipart_threshold = 3GB
    
now it failed at first time always. and try again sometime completed.


error happen 
`2024-04-23T11:28:49.288 ERROR --- [ead-4 (_run)] localstack_persist.state   : Error while persisting state of service s3
localstack_container  | Traceback (most recent call last):
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persist/state.py", line 114, in save_all_services_state
localstack_container  |     self._save_service_state(service_name)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persist/state.py", line 165, in _save_service_state
localstack_container  |     service.accept_state_visitor(SaveStateVisitor(service_name))
localstack_container  |   File "/opt/code/localstack/localstack/services/plugins.py", line 133, in accept_state_visitor
localstack_container  |     self._provider.accept_state_visitor(visitor)
localstack_container  |   File "/opt/code/localstack/localstack/services/s3/v3/provider.py", line 312, in accept_state_visitor
localstack_container  |     visitor.visit(s3_stores)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persist/visitors.py", line 145, in visit
localstack_container  |     self._save_state(state_container)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persist/visitors.py", line 166, in _save_state
localstack_container  |     serializer.serialize(state_container)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/localstack_persist/serialization/jsonpickle/serializer.py", line 30, in serialize
localstack_container  |     envelope = {SER_VERSION_KEY: SER_VERSION, DATA_KEY: pickler.flatten(data)}
localstack_container  |                                                         ^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 336, in flatten
localstack_container  |     return self._flatten(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 675, in _ref_obj_instance
localstack_container  |     return self._flatten_obj_instance(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 638, in _flatten_obj_instance
localstack_container  |     self._flatten_dict_obj(obj, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 675, in _ref_obj_instance
localstack_container  |     return self._flatten_obj_instance(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 638, in _flatten_obj_instance
localstack_container  |     self._flatten_dict_obj(obj, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 675, in _ref_obj_instance
localstack_container  |     return self._flatten_obj_instance(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 656, in _flatten_obj_instance
localstack_container  |     return self._flatten_dict_obj(obj.__dict__, data)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 675, in _ref_obj_instance
localstack_container  |     return self._flatten_obj_instance(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 656, in _flatten_obj_instance
localstack_container  |     return self._flatten_dict_obj(obj.__dict__, data)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 675, in _ref_obj_instance
localstack_container  |     return self._flatten_obj_instance(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 656, in _flatten_obj_instance
localstack_container  |     return self._flatten_dict_obj(obj.__dict__, data)
localstack_container  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 744, in _flatten_dict_obj
localstack_container  |     flatten(k, v, data)
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 730, in _flatten_string_key_value_pair
localstack_container  |     data[k] = self._flatten(v)
localstack_container  |               ^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 296, in _flatten
localstack_container  |     result = self._flatten_impl(obj)
localstack_container  |              ^^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 356, in _flatten_impl
localstack_container  |     return self._pop(self._flatten_obj(obj))
localstack_container  |                      ^^^^^^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 389, in _flatten_obj
localstack_container  |     raise e
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 383, in _flatten_obj
localstack_container  |     return flatten_func(obj)
localstack_container  |            ^^^^^^^^^^^^^^^^^
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/pickler.py", line 743, in _flatten_dict_obj
localstack_container  |     for k, v in util.items(obj):
localstack_container  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/jsonpickle/util.py", line 560, in items
localstack_container  |     for k, v in obj.items():
localstack_container  | RuntimeError: dictionary changed size during iteration`


this is when completed upload happened log
`localstack_container  | 2024-04-23T11:31:01.895 ERROR --- [  asgi_gw_15] l.aws.handlers.logging     : exception during call chain: [Errno 2] No such file or directory: '/persisted-data/s3/assets/local-uw2-s3-bg-patch/multiparts/j0WKZXu0zhE3dxwTmG-gTnugZiXvz5uKUEAyftQJ_qJaMruVxDEvA9ndN8HUiNJVSQDlucRvcmWmyGEej4l1MzaK7lWxKiWm6ZEzCpngNQgWvegpQT9RXO-i5UH_sExh/part-127'
localstack_container  | 2024-04-23T11:31:01.896  INFO --- [  asgi_gw_15] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 500 (InternalError)
localstack_container  | 2024-04-23T11:31:02.365  INFO --- [   asgi_gw_3] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 200
localstack_container  | 2024-04-23T11:31:02.637  INFO --- [  asgi_gw_10] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 404 (NoSuchUpload)
localstack_container  | 2024-04-23T11:31:02.650  INFO --- [  asgi_gw_13] localstack.request.aws     : AWS s3.AbortMultipartUpload => 404 (NoSuchUpload)
localstack_container  | 2024-04-23T11:31:05.856  INFO --- [ead-4 (_run)] localstack_persist.state   : Persisting state of service s3...
localstack_container  | 2024-04-23T11:31:16.513  INFO --- [   asgi_gw_8] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 200
localstack_container  | 2024-04-23T11:31:16.660 ERROR --- [   asgi_gw_1] l.aws.handlers.logging     : exception during call chain: [Errno 2] No such file or directory: '/persisted-data/s3/assets/local-uw2-s3-bg-patch/multiparts/Hmlrlfp0VlEsn1OSmAXiAoYzy8XvwpQhi8ARrHahCOGGZhswxerKjNHG5pCxgGYhECSdUDEX8eJJu5n-IgrMYDLmVJrXLUK7_a1_F7hVi78LbX9kuBMPaWigSVHyJbpa/part-52'
localstack_container  | 2024-04-23T11:31:16.662  INFO --- [   asgi_gw_1] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 500 (InternalError)
localstack_container  | 2024-04-23T11:31:16.920  INFO --- [  asgi_gw_11] localstack.request.aws     : AWS s3.CompleteMultipartUpload => 404 (NoSuchUpload)
localstack_container  | 2024-04-23T11:31:16.942  INFO --- [  asgi_gw_16] localstack.request.aws     : AWS s3.AbortMultipartUpload => 404 (NoSuchUpload)
localstack_container  | 2024-04-23T11:31:17.780  INFO --- [ead-4 (_run)] localstack_persist.state   : Persisting state of service s3...`

**Comment by GREsau** [comment]
Could you run `docker inspect gresau/localstack-persist:latest --format "{{.Created}}"` and tell me the output? Then I can correlate it with the build that produced it to see what underlying version is being used

**Comment by kybird** [comment]
here is the result
F:\Docker\infra>docker inspect gresau/localstack-persist:latest --format "{{.Created}}"
2024-04-22T18:39:27.354322895Z

**Comment by GREsau** [comment]
I think there are actually two separate bugs at play here:

### 1. A service's state can be modified while it's being persisted

This is what causes `RuntimeError: dictionary changed size during iteration`. It's more likely to occur when making many requests very quickly, which could occur when performing a multipart upload or even when uploading lots of small files. This is definitely a genuine bug in localstack-persist, and I'll try to fix it ASAP by adding some more locking.

### 2. Completing a multipart upload is slow, which can cause the AWS SDK/CLI to timeout and retry

This is what causes `No such file or directory: '/persisted-data/s3/assets/local-uw2-s3-bg-patch/multiparts/...`, ` AWS s3.CompleteMultipartUpload => 500 (InternalError)` and `AWS s3.CompleteMultipartUpload => 404 (NoSuchUpload)`. A [CompleteMultipartUpload](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html) request may take several minutes to complete in real AWS, so AWS periodically sends whitespace chars over the HTTP response to keep the connection alive. LocalStack does not do this, so the connection may time out, which will typically cause the client to retry the request. The retry may then fail, and the previous attempt may have already completed the multipart and cleaned up the original parts (i.e. the request is not idempotent).

This second bug is much more difficult to fix, especially because it's technically a bug in LocalStack itself, rather than in localstack-persist. But I don't think it affects plain LocalStack as much as it does localstack-persist, for two reasons:
1. localstack-persist stores S3 files in a docker bind mount, which is much slower than the regular filesystem in a docker container. This causes the `CompleteMultipartUpload` handling take longer
2. the default ephemeral S3 storage used by LocalStack (not localstack-persist) does not clean up the parts after a multipart upload is completed (https://github.com/localstack/localstack/blob/fcd5927e16f158ca0449c1194a151a12983f805a/localstack/services/s3/v3/storage/ephemeral.py#L295-L310). This makes it more idempotent, so if a request times out and a retry does occur, then the retry won't fail (unless it also times out, of course!). 

However, you can probably work-around this second bug by increasing the client read timeout. e.g. if you're using the AWS CLI, you could set `--cli-read-timeout 180` to increase the timeout to 3 min.

**Comment by GREsau** [comment]
`localstack-persist:latest` and `localstack-persist:3.4.0` both now have a fix for the first bug, so if you update your container's image then you should no longer get `RuntimeError: dictionary changed size during iteration`. Does that fix your problem?

**Comment by kybird** [comment]
Thanks for detail describe!!!!.

i was avoid this problem by reduce the size of the file. 2G -> 1.5G and it works. i don't know why
and now i pulled your new image. and test it with over 2G file.

yes there is no more  below one 
```
RuntimeError: dictionary changed size during iteration
```

yes i using WSL2 and it mount windows filesystem. so it must be very slow. i think...

and it failed with
```
An error occurred (NoSuchUpload) when calling the CompleteMultipartUpload operation: The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.
```

i'll add the timeout parameter. test again. omg it worked!!!
no problem.

thanks for your support!
