### ISSUE TITLE
Missing SQS queue attributes after container restart

### ISSUE THREAD

**Issue by pm-incyan** [GREsau/localstack-persist#15]
Thanks for making this, a very helpful little tool!

I've been using SQS, and I notice when running normally, SQS queue attributes work as expected, but if you restart the container, most of the attributes come back as you would expect, however the following 3 queue attribute disappear post-restart:

```
{
    "Attributes": {
        "ApproximateNumberOfMessages": "123",
        "ApproximateNumberOfMessagesNotVisible": "10",
        "ApproximateNumberOfMessagesDelayed": "0"
    }
}
```

Thank you!

**Comment by GREsau** [comment]
Thanks for the report, this should now be fixed in localstack-persist 4.0.2 🙂
