### ISSUE TITLE
Any chance of exposing the persist/save rate?

### ISSUE THREAD

**Issue by Chargeuk** [GREsau/localstack-persist#17]
Hi,
first I would just like to thank you on creating such a great version of localstack. I was in the process of upgrading from 2.x when I found that the pod load and save options I was relying on had been removed.

Looking at issue [https://github.com/GREsau/localstack-persist/issues/8](https://github.com/GREsau/localstack-persist/issues/8), you mention that localstack-persist is configured to write the data on a schedule, which is currently 10 seconds. Would it be possible to expose that parameter so we can override it? I would like to reduce the frequency so that I don't continuously hammer my SSD.

Many thanks again on a this great fork.

**Comment by GREsau** [comment]
This is implemented in localstack-persist 4.0.4 - you can now set the `PERSIST_FREQUENCY` environment variable to the desired frequency (in seconds) 🙂

**Comment by Chargeuk** [comment]
That's great, thanks for the update. Funny - I was just in the middle of implementing this myself 🙂
I also would like to add another concept - the ability for a service to load, but not persist. I need this for running my tests, where I have an environment set up in with all the S3 buckets and SQS queues ready for the test run, and I want them to be updated in memory while the test is running, but when it's restarted, I would like it to go back to the initial state. Hopefully I will open that pull request later today or sometime tomorrow.
Thanks again.

**Comment by Chargeuk** [comment]
@GREsau - here you go: https://github.com/GREsau/localstack-persist/pull/18
