### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by lucasnicoleto** [GREsau/localstack-persist#9]
Hey mate

First thanks for this, it has helped a lot.

Question 

Can you support SSL ? 

I tried to pass the env variable 
-e USE_SSL=1

but it seems it is not working. 

can you take a look ? 

Really thanks

**Comment by GREsau** [comment]
What do you mean by "support SSL", and in what way is it "not working"? Are you trying to do something that works in normal localstack, but behaves differently in localstack-persist with a comparable version?

**Comment by lucasnicoleto** [comment]
Hey Mate,
Sorry, I wasn't clear. 

Yes.

Basically I want to have the localstack running with your image using the variable USE_SSL=1 to use https, ex  https://localhost:4566
When I use your image and add the variable USE_SSL=1 it isn't working. 
When I use the localstack image itself, with this variable it works.

**Comment by lucasnicoleto** [comment]
It is working, it was my mistake, sorry.
